### ISSUE TITLE
Вынести шкафы

### ISSUE THREAD

**Issue by Blucknote** [Blucknote/-#1]
- [ ] Раздербанить шкафы

- [ ] Вынести
- [ ] ???
- [ ] PROFIT
- [ ] Бургерович

**Comment by funaska** [comment]
Бургерович слишком далеко от сходненской...
Предлагаю, например, додо пиицу - мы их попробовали недавно и они огонь!

**Comment by Blucknote** [comment]
@funaska 
Я слышал не лестные отзывы о них.
Или это о доминос?

**Comment by Blucknote** [comment]
@funaska похоже issue все таки контрибьюторам редактировать нельзя, но я сделал список, как хотел)
https://github.com/Blucknote/-
